<?php
$tech = $this->getProduct()->getData('features');
$info = json_decode($tech, true);
$count = 1;
?>

<div id="features_container">
    <?php if (count($info) > 0) : ?>
    <?php foreach ($info as $i) : ?>
            <?php if (isset($i['name']) && isset($i['desc'])) : ?>
                <div style="margin:auto" class="gradus_fields" id="features_<?= $count ?>">
                    <div class="draggable-handle features_drag"><b><?= $count ?></b></div>
                    <label class="gradus_label" for="feat_n_<?= $count ?>">Label</label>
                    <input style="margin-bottom:5px;" name="features[<?= $count ?>][name]" data-form-part="product_form" class="gradus_text_large" id="feat_n_<?= $count ?>" value="<?= $i['name'] ?>" />
                    <div style="line-break:auto" />
                    <label style="margin-left:18px" class="gradus_label" for="feat_d_<?= $count ?>">Feature</label>
                    <textarea data-form-part="product_form" name="features[<?= $count?>][desc]" style="margin-top:5px; width:79.5%;" class="gradus_text_large" id="feat_d_<?= $count ?>">
                        <?= $i['desc'] ?></textarea>
                    <a src="javascript:void(0)" onclick="deleteFeature('features_<?= $count ?>')">
                        <img style="width:20px;" src="<?= $this->getViewFileUrl('Gradus_Catalog::images/trash.png') ?>">
                    </a>
                    <?php $count++ ?>
                </div>
            <?php endif ?>
    <?php endforeach ?>
    <?php endif ?>
</div>
<button class="action-secondary" style="margin-right:5px;" onclick="addFeature()">Add Feature</button>
<div class="select_pad">
    <select class="search_select" id="copy_from_feature">
        <option value="-1">SKU | Name</option>
        <?php foreach ($this->getProducts() as $p) : ?>
            <option value="<?= $p->getId() ?>"><?= $p->getSku() ?> | <?= $p->getName() ?></option>
        <?php endforeach; ?>
    </select>
    <button class="action-secondary" onclick="copyfeature()">Copy from</button>
</div>

<script>
    var $q = jQuery.noConflict();

    function copy()
    {
        var theid = $q('#copy_from').val();
        $q.ajax({
            url: 'http://'+window.location.hostname+"/admin/catalog/product/copy/id/"+theid+"/field/features/",
            data: {form_key: window.FORM_KEY},
            context: document.body
        }).done(function(res) {
            var q = res.res;
            $q('#features_container').html(q);
        });
    }

    $q( document ).ready(function() {
        $q('#features_container').sortable({
            handle: '.draggable-handle',
            revert: 300,
            placeholder: "jqplaceholder",
            tolerance: "intersect",
            update: function( event, ui ) {
                $q('.features_drag').each(function(i, obj) {
                    var ii = i+1;
                    $q(this).html(ii);
                })
            }
        }).disableSelection();
    });
    function addFeature()
    {
        var counts = $q('#features_container input').length;
        var clb = counts+1;
        var q = '';
        q += '<div style="margin:auto" class="gradus_fields" id="features_'+clb+'">';
        q += '<div class="draggable-handle features_drag"><b>'+clb+'</b></div>';
        q += '<label class="gradus_label" for="feat_n_'+clb+'">Label</label>';
        q += '<input style="margin-bottom:5px" name="features['+clb+'][name]" data-form-part="product_form" class="gradus_text_large" id="feat_n_'+clb+'" value="" />';
        q += '<div style="line-break:auto" />';
        q += '<label style="margin-left:18px" class="gradus_label" for="feat_d_'+clb+'">Feature</label>';
        q += '<textarea data-form-part="product_form" name="features['+clb+'][desc]" style="width:79.5%; top-margin:5px;" data-form-part="product_form" class="gradus_text_large" id="feat_d_'+clb+'>" value=""></textarea>';
        q += '<a src="javascript:void(0)" style="margin-left:6px;" onclick="deleteFeature(\'features_'+clb+'\')">';
        q += '<img style="width:20px;" src="<?= $this->getViewFileUrl('Gradus_Catalog::images/trash.png') ?>"></a></div>';

        $q('#features_container').append
        (q);
    }

    function deleteFeature(h)
    {
        $q('#'+h).remove();
        $q('.features_drag').each(function(i, obj) {
            var ii = i+1;
            $q(this).html(ii);
        });
    }
</script>