<?php
$tech = $this->getProduct()->getData('features');
$info = json_decode($tech, true);
$count = 1;

?>
<div style="width:800px;" id="features_container">
    <table id="features_table" class="admin__dynamic-rows data-grid">
        <thead>
        <tr>
            <th class="data-grid-draggable-row-cell"></th>
            <th class="data-grid-th position" style="width:30px"><span>Seq</span></th>
            <th class="data-grid-th"><span>Feature Label</span></th>
            <th class="data-grid-th"><span>Feature Value</span></th>
            <th style="width:40px"/>
        </tr>
        </thead>
        <tbody>
        <?php if (count($info) > 0) : ?>
        <?php foreach ($info as $i) : ?>
            <tr id="features_row_<?= $count ?>">
                <td class=""data-grid-draggable-row-cell">
                <div class="draggable-handle_features"></div>
                </td>
                <td class="posrow">
                    <?= $count ?>
                </td>
                <td>
                    <input class="admin__control-text" name="features[<?= $count ?>][name]" data-form-part="product_form" name="features[<?= $count ?>[name]" style="width:100%; padding:3px;" value="<?= $i["name"] ?>" />
                </td>
                <td><textarea name="features[<?= $count?>][desc]" data-form-part="product_form" style="width:100%;"><?= $i['desc'] ?></textarea></td>
                <td><a onclick="deleteFeature('features_row_<?= $count ?>')" href"#"><img src="<?= $this->getViewFileUrl('Gradus_Catalog::images/trash.png'); ?>" style="width:20px"></a></td>
            </tr>
            <?php $count++ ?>
        <?php endforeach; ?>
        </tbody>
    </table>
    <?php else : ?>
        <tr id="features_row_<?= $count ?>">
            <td class=""data-grid-draggable-row-cell">
            <div class="draggable-handle_features"></div>
            </td>
            <td class="posrow">
                <?= $count ?>
            </td>
            <td>
                <input class="admin__control-text" name="features[<?= $count ?>][name]" data-form-part="product_form" name="features[<?= $count ?>[name]" style="width:100%;" value="" />
            </td>
            <td><textarea id="qwerty" name="features[<?= $count?>][desc]" data-form-part="product_form" style="width:100%;"></textarea></td>
            <td><a onclick="deleteFeature('features_row_<?= $count ?>')" href"#"><img src="<?= $this->getViewFileUrl('Gradus_Catalog::images/trash.png'); ?>" style="width:20px"></a></td>
        </tr>
    <?php endif ?>
</div>

<button class="action-secondary" style="margin-right:5px; margin-bottom: 5px;" onclick="addFeature()">Add Feature</button>
<div style="display:none" class="select_pad">
    <select class="search_select" id="copy_from_feature">
        <option value="-1">SKU | Name</option>
        <?php foreach ($this->getProducts() as $p) : ?>
            <option value="<?= $p->getId() ?>"><?= $p->getSku() ?> | <?= $p->getName() ?></option>
        <?php endforeach; ?>
    </select>
    <button class="action-secondary" onclick="copyfeature()">Copy from</button>
</div>

<script>
    var $q = jQuery.noConflict();

    function copy()
    {
        var theid = $q('#copy_from').val();
        $q.ajax({
            url: 'http://'+window.location.hostname+"/admin/catalog/product/copy/id/"+theid+"/field/features/",
            data: {form_key: window.FORM_KEY},
            context: document.body
        }).done(function(res) {
            var q = res.res;
            $q('#features_container').html(q);
        });
    }

    $q( document ).ready(function() {
        $q('#features_table > tbody').sortable({
            handle: '.draggable-handle_features',
            revert: 300,
            placeholder: "jqplaceholder",
            tolerance: "intersect",
        }).disableSelection();
    });
    function addFeature()
    {
        var counts = $q('#features_table > tbody > tr').length;
        var clb = counts+1;
        q = '<tr id="features_row_'+clb+'">'+
            '<td class="data-grid-draggable-row-cell">'+
            '<div class="draggable-handle_features"></div></td>'+
            '<td class="posrow">'+clb+'</td><td>'+
            '<input class="admin__control-text" name="features['+clb+'][name]" data-form-part="product_form" id="features[' + clb + '][name]" style="width:100%;" value="" /></td>'+
                '<td><textarea id="qwerty" name="features['+clb+'][desc]" data-form-part="product_form" style="width:100%;"></textarea></td>'+
            '</td><td><a href"#" onclick="deleteFeature(\'features_row_'+clb+'\')"><img src="<?= $this->getViewFileUrl('Gradus_Catalog::images/trash.png'); ?>" style="width:20px"></a></td></tr>';
        $q('#features_table > tbody').append(q);
    }

    function deleteFeature(h)
    {
        $q('#'+h).remove();
        $q('.features_drag').each(function(i, obj) {
            var ii = i+1;
            $q(this).html(ii);
        });
    }
</script>