<?php
$tech = $this->getProduct()->getData('features');
$info = json_decode($tech, true);
$count = 1;

?>
<div style="width:800px;" id="features_container">
    <table id="features_table" class="admin__dynamic-rows data-grid">
        <thead>
        <tr>
            <th class="data-grid-draggable-row-cell"></th>
            <th class="data-grid-th position" style="width:30px"><span>Seq</span></th>
            <th class="data-grid-th"><span>Feature Label</span></th>
            <th class="data-grid-th"><span>Feature Value</span></th>
            <th style="width:40px"/>
        </tr>
        </thead>
        <tbody>
        <?php if (count($info) > 0) : ?>
        <?php foreach ($info as $i) : ?>
            <tr id="features_row_<?= $count ?>">
                <td class=""data-grid-draggable-row-cell">
                <div class="draggable-handle_features"></div>
                </td>
                <td class="posrow">
                    <?= $count ?>
                </td>
                <td>
                    <input class="admin__control-text" name="features[<?= $count ?>][name]" data-form-part="product_form" name="features[<?= $count ?>[name]"
                           style="width:100%; padding:3px;" value="<?php if (isset($i["name"])) { echo $i['name']; } ?>" />
                </td>
                <td><textarea class="wysiwyg" name="features[<?= $count?>][desc]" data-form-part="product_form" style="width:100%;"><?php if (isset($i['desc'])) { echo $i['desc']; } ?></textarea></td>
                <td><a onclick="deleteFeature('features_row_<?= $count ?>')" href"#"><img src="<?= $this->getViewFileUrl('Gradus_Catalog::images/trash.png'); ?>" style="width:20px"></a></td>
            </tr>
            <?php $count++ ?>
        <?php endforeach; ?>
        </tbody>
    </table>
    <?php else : ?>
        <tr id="features_row_<?= $count ?>">
            <td class=""data-grid-draggable-row-cell">
            <div class="draggable-handle_features"></div>
            </td>
            <td class="posrow">
                <?= $count ?>
            </td>
            <td>
                <input class="admin__control-text" name="features[<?= $count ?>][name]" data-form-part="product_form" name="features[<?= $count ?>[name]" style="width:100%;" value="" />
            </td>
            <td><textarea class="wysiwyg" name="features[<?= $count?>][desc]" data-form-part="product_form" style="width:100%;"></textarea></td>
            <td><a onclick="deleteFeature('features_row_<?= $count ?>')" href"#"><img src="<?= $this->getViewFileUrl('Gradus_Catalog::images/trash.png'); ?>" style="width:20px"></a></td>
        </tr>
    <?php endif ?>
</div>

<button class="action-secondary" style="margin-right:5px; margin-bottom: 5px;" onclick="addFeature('', '')">Add Feature</button>
<div style="display:none" class="select_pad">
    <select class="search_select" id="copy_from_feature">
        <option value="-1">SKU | Name</option>
        <?php foreach ($this->getProducts() as $p) : ?>
            <option value="<?= $p->getId() ?>"><?= $p->getSku() ?> | <?= $p->getName() ?></option>
        <?php endforeach; ?>
    </select>
    <button class="action-secondary" onclick="copyfeature()">Copy from</button>
</div>

<script>
    var $q = jQuery.noConflict();

    $q( document ).ready(function() {
        initMce();
        initSortable();
    });

    function initMce() {
        console.log("Initing MCE");
        tinyMCE.init({
            mode: "textareas",
            elements: "wysiwyg",
            theme_advanced_toolbar_align: "left",
            theme_advanced_path_location: "bottom",
            extended_valid_elements: "a[name|href|target|title|onclick],img[class|src|border=0|alt|title|hspace|vspace|width|height|align|onmouseover|onmouseout|name],hr[class|width|size|noshade],font[face|size|color|style],span[class|align|style]",
            theme_advanced_resize_horizontal: 'true',
            theme_advanced_resizing: 'true',
            apply_source_formatting: 'true',
            convert_urls: 'true',
            force_br_newlines: 'true',
            width: '100%',
            min_width: 0
        });
    }
    function initSortable()
    {
        $q('#features_table > tbody').sortable({
            handle: '.draggable-handle_features',
            revert: 300,
            placeholder: "jqplaceholder",
            tolerance: "intersect",
        }).disableSelection();
    }
    function addFeature(label, value)
    {
        var counts = $q('#features_table > tbody > tr').length;
        var clb = counts+1;
        q = '<tr id="features_row_'+clb+'">'+
            '<td class="data-grid-draggable-row-cell">'+
            '<div class="draggable-handle_features"></div></td>'+
            '<td class="posrow">'+clb+'</td><td>'+
            '<input class="admin__control-text" name="features['+clb+'][name]" data-form-part="product_form" id="features[' + clb + '][name]" style="width:100%;" value="'+label+'" /></td>'+
                '<td><textarea class="wysiwyg" name="features['+clb+'][desc]" data-form-part="product_form" style="width:100%;">'+value+'</textarea></td>'+
            '</td><td><a href"#" onclick="deleteFeature(\'features_row_'+clb+'\')"><img src="<?= $this->getViewFileUrl('Gradus_Catalog::images/trash.png'); ?>" style="width:20px"></a></td></tr>';
        $q('#features_table > tbody').append(q);
        initMce();
    }

    function copyFeatures(vals)
    {
        jQuery('#features_table > tbody').empty();
        $q.each(vals, function(i, v) {
            $q.each(v, function(ii, vv) {
                if (ii == 'name') {
                    vals['c'] = vv;
                }
                if (ii == 'desc') {
                    vals['v'] = vv;
                }
            })
            if (typeof(vals['c']) != "undefined" && vals['c'] !== null) {
                addFeature(vals['c'], vals['v']);
            }
        });
        initMce();
    }

    function deleteFeature(h)
    {
        $q('#'+h).remove();
        $q('.features_drag').each(function(i, obj) {
            var ii = i+1;
            $q(this).html(ii);
        });
    }
</script>