<?php
$tech = $this->getProduct()->getData('in_the_box');
$info = json_decode($tech, true);
$count = 1;
?>
<div id="in_the_box_container">
    <?php if (count($info) > 0) : ?>
    <?php foreach ($info as $i) : ?>
            <?php if (!is_null($i)) : ?>
                <div style="margin:auto" class="gradus_fields" id="in_the_box_<?= $count ?>">
                    <div class="draggable-handle inthebox_drag"><b><?= $count ?></b></div>
                    <label class="gradus_label" for="in_the_box_amount_<?= $count ?>">Amount</label>
                    <input name="in_the_box[<?= $count ?>][count]" data-form-part="product_form" class="gradus_text_mini" id="in_the_box_amount_<?= $count ?>" value="<?= $i['count'] ?>" />
                    <label class="gradus_label" for="in_the_box_value_<?= $count ?>">Item</label>
                    <input name="in_the_box[<?= $count ?>][value]" data-form-part="product_form" class="gradus_text_medium" style="width:70%"
                           id="in_the_box_value_<?= $count ?>" value="<?= $i['value'] ?>" />
                    <a src="javascript:void(0)" onclick="deleteinthebox('in_the_box_<?= $count ?>')">
                        <img style="width:20px;" src="<?= $this->getViewFileUrl('Gradus_Catalog::images/trash.png') ?>">
                    </a>
                    <?php $count++ ?>
                </div>
            <?php endif ?>
        <?php endforeach ?>
    <?php endif ?>
</div>
<button class="action-secondary" style="margin-right:5px;" onclick="addinthebox()">Add Include</button>
<div class="select_pad">
    <select class="search_select" id="copy_from_inthebox">
        <option value="-1">SKU | Name</option>
        <?php foreach ($this->getProducts() as $p) : ?>
            <option value="<?= $p->getId() ?>"><?= $p->getSku() ?> | <?= $p->getName() ?></option>
        <?php endforeach; ?>
    </select>
    <button class="action-secondary" onclick="copyinthebox()">Copy from</button>
</div>

<script>
    var $q = jQuery.noConflict();

    function copyinthebox()
    {
        var theid = $q('#copy_from_inthebox').val();
        $q.ajax({
            url: 'http://'+window.location.hostname+"/admin/catalog/product/copy/id/"+theid+"/field/inthebox/",
            data: {form_key: window.FORM_KEY},
            context: document.body
        }).done(function(res) {
            var q = res.res;
            $q('#in_the_box_container').html(q);
        });
    }

    $q( document ).ready(function() {
        $q('#in_the_box_container').sortable({
            handle: '.draggable-handle',
            revert: 300,
            placeholder: "jqplaceholder",
            tolerance: "intersect",
            update: function( event, ui ) {
                $q('.inthebox_drag').each(function(i, obj) {
                    var ii = i+1;
                    $q(this).html(ii);
                })
            }
        }).disableSelection();
    });
    function addinthebox()
    {
        var counts = $q('#in_the_box_container .draggable-handle').length;
        var clb = counts+1;
        var q = '';
        q += '<div style="margin:auto" class="gradus_fields" id="in_the_box_'+clb+'">';
        q += ' <div class="draggable-handle inthebox_drag"><b>'+clb+'</b></div>';
        q += '<label class="gradus_label" for="in_the_box_amount_'+clb+'">Amount</label>';
        q += '<input name="in_the_box['+clb+'][count]" data-form-part="product_form" style="margin-left:6px;" class="gradus_text_mini" id="in_the_box_amount_'+clb+'" value="" />';
        q += '<label class="gradus_label" for="in_the_box_value_'+clb+'">Item</label>';
        q += '<input name="in_the_box['+clb+'][value]" data-form-part="product_form" style="margin-left:6px; width:70%" class="gradus_text_medium" style="width:70%" id="in_the_box_value_'+clb+'" value="" />';
        q += '<a src="javascript:void(0)" style="margin-left:6px;" onclick="deleteinthebox(\'in_the_box_'+clb+'\')">';
        q += '<img style="width:20px;" src="<?= $this->getViewFileUrl('Gradus_Catalog::images/trash.png') ?>"></a></div>';
        $q('#in_the_box_container').append
        (q);
    }

    function deleteinthebox(h)
    {
        $q('#'+h).remove();
        $q('.inthebox_drag').each(function(i, obj) {
            var ii = i+1;
            $q(this).html(ii);
        });
    }
</script>