<?php
$tech = $this->getProduct()->getData('in_the_box');
$info = json_decode($tech, true);
$count = 1;
$manual = 0;
if (count($info) > 0) {
    foreach ($info as $i) {
        if (isset($i['has_manual'])) {
            $manual = (int)$i['has_manual'];
            unset($i);
        }
    }
}
$warranty = $this->getProduct()->getData('warranty');
if ($warranty < 12) {
    $warrantyString = $warranty." months.";
} else {
    $warrantyString = (int)($warranty/12)." year(s).";
}
if ($warranty == null) { $warrantyString = "No warranty"; }
?>
<div style="width:800px;" id="InTheBox_container">
    <table id="InTheBox_table" class="admin__dynamic-rows data-grid">
        <thead>
        <tr>
            <th class="data-grid-draggable-row-cell"></th>
            <th class="data-grid-th position" style="width:30px"><span>Seq</span></th>
            <th class="data-grid-th" style="width:50px;"><span>Include Count</span></th>
            <th class="data-grid-th"><span>Include Value</span></th>
            <th style="width:40px"/>
        </tr>
        </thead>
        <tbody>
        <?php if (count($info) > 0) : ?>
        <?php foreach ($info as $i) : ?>
            <?php if (isset($i['has_manual'])) { $manual = $i['has_manual']; continue; } ?>
            <tr id="inthebox_row_<?= $count ?>">
                <td class=""data-grid-draggable-row-cell">
                <div class="draggable-handle_inthebox"></div>
                </td>
                <td class="posrow">
                    <?= $count ?>
                </td>
                <td>
                    <input class="admin__control-text" name="inthebox[<?= $count ?>][count]" data-form-part="product_form" name="inthebox[<?= $count ?>[count]" style="width:100%;" value="<?= $i["count"] ?>" />
                </td>
                <td><textarea name="inthebox[<?= $count?>][value]" data-form-part="product_form" style="width:100%;"><?= $i['value'] ?></textarea></td>
                <td><a onclick="deleteinthebox('inthebox_row_<?= $count ?>')" href"#"><img src="<?= $this->getViewFileUrl('Gradus_Catalog::images/trash.png'); ?>" style="width:20px"></a></td>
            </tr>
            <?php $count++ ?>
        <?php endforeach; ?>
        </tbody>
    </table>
    <?php else : ?>
        <tr id="inthebox_row<?= $count ?>">
            <td class=""data-grid-draggable-row-cell">
            <div class="draggable-handle_inthebox"></div>
            </td>
            <td class="posrow">
                <?= $count ?>
            </td>
            <td>
                <input class="admin__control-text" name="inthebox[<?= $count ?>][count]" data-form-part="product_form" style="width:100%;" value="" />
            </td>
            <td><textarea name="inthebox[<?= $count?>][value]" data-form-part="product_form" style="width:100%;"></textarea></td>
            <td><a onclick="deleteFeature('inthebox_row_<?= $count ?>')" href"#"><img src="<?= $this->getViewFileUrl('Gradus_Catalog::images/trash.png'); ?>" style="width:20px"></a></td>
        </tr>
    <?php endif ?>
</div>

<?php if ($manual > 0) : ?>
<input checked name="manual_check" data-form-part="product_form" type="checkbox"/><div style="display:inline-block; margin-left:5px;">Includes manual</div>
<?php else : ?>
    <input name="manual_check" data-form-part="product_form" type="checkbox"/><div style="display:inline-block; margin-left:5px;">Includes manual</div>
<?php endif ?>
<br>
<div style="font-size: 1.4rem; font-weight: 600;">Warranty: <?= $warrantyString ?></div>
<br>
<button class="action-secondary" style="margin-right:5px; margin-top:5px" onclick="addinthebox()">Add InTheBox</button>
<div style="display:none;" class="select_pad">
    <select class="search_select" id="copy_from_inthebox">
        <option value="-1">SKU | Name</option>
        <?php foreach ($this->getProducts() as $p) : ?>
            <option value="<?= $p->getId() ?>"><?= $p->getSku() ?> | <?= $p->getName() ?></option>
        <?php endforeach; ?>
    </select>
    <button class="action-secondary" onclick="copyinthebox()">Copy from</button>
</div>

<script>
    var $q = jQuery.noConflict();
    $q( document ).ready(function() {
        $q('#InTheBox_table > tbody').sortable({
            handle: '.draggable-handle_inthebox',
            revert: 300,
            placeholder: "ui-state-in_the_box myHover",
            tolerance: "intersect",
        }).disableSelection();
    });
    function addinthebox()
    {
        var counts = $q('#InTheBox_table > tbody > tr').length;
        var clb = counts+1;
        q = '<tr id="inthebox_row_'+clb+'">'+
            '<td class="data-grid-draggable-row-cell">'+
            '<div class="draggable-handle_inthebox"></div></td>'+
            '<td class="posrow">'+clb+'</td><td>'+
            '<input class="admin__control-text" name="inthebox['+clb+'][count]" data-form-part="product_form" id="inthebox[' + clb + '][count]" style="width:100%;" value="" /></td>'+
            '<td><textarea name="inthebox['+clb+'][value]" data-form-part="product_form" style="width:100%;"></textarea></td>'+
            '</td><td><a href"#" onclick="deleteinthebox(\'inthebox_row_'+clb+'\')"><img src="<?= $this->getViewFileUrl('Gradus_Catalog::images/trash.png'); ?>" style="width:20px"></a></td></tr>';
        $q('#InTheBox_table > tbody').append(q);
    }

    function deleteinthebox(h)
    {
        $q('#'+h).remove();
    }

    function copyinthebox()
    {
        var theid = $q('#copy_from_inthebox').val();
        $q.ajax({
            url: 'http://'+window.location.hostname+"/admin/catalog/product/copy/id/"+theid+"/field/inthebox/",
            data: {form_key: window.FORM_KEY},
            context: document.body
        }).done(function(res) {
            var q = res.res;
            $q('#InTheBox_container').html(q);
            updateaccord();
            updateaccord();
        });
    }
</script>