<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php if ($block->getChildHtml()):?>
    <div data-mage-init='{"floatingHeader": {}}' class="page-actions" <?php /* @escapeNotVerified */ echo $block->getUiId('content-header') ?>>
        <?php echo $block->getChildHtml(); ?>
    </div>

    <div id="copy_from_div">
        <div id="searchContainer" style="border:1px solid; width:750px; padding:10px;">
            <div class="admin__action-multiselect-search-wrap" style="width:400px; display:inline-block">
                <input onkeyup="getHighlightSearch()" id="highlight_search" class="admin__control-text admin__action-multiselect-search" type="text">
                <label class="admin__action-multiselect-search-label"></label>
            </div>
            <select multiple style="display: inline-block; max-height:250px; overflow:auto;" id="copy_items">
                <option value="name">Name</option>
                <option value="categories">Categories</option>
                <option value="highlights">Highlights</option>
                <option value="techspecs">Specifications</option>
                <option value="description">Description</option>
                <option value="InTheBox">Includes</option>
                <option value="features">Features</option>
                <option value="images">Images & Videos</option>
                <option value="seo">Seo Information</option>
                <option value="related">Related Products</option>
                <option value="accessories">Accessories</option>
                <option value="compatibility">Compatibility</option>
                <option values="downloads">Downloadable Files</option>
            </select>
            <button type="button" class="action-secondary" onclick="runCopy()" style="display:inline-block">Copy fields</button>
            <div  style="display:none;">
                <input id="searchPicked" />
            </div>
            <br>
            Selected MFR <div id="picked"></div>
            <div id="highlight_results" style="max-height:250px; overflow:auto;">

            </div>
        </div>
    </div>

<script>
    var $q = jQuery.noConflict();

    function toggleCopy()
    {
        $q('#copy_from_div').toggle();
    }

    function runCopy()
    {
    var fields = $q('#copy_items').val();
    var item = $q('#searchPicked').val();
    if (item == "") {
    alert("Please choose an item to copy from!");
    return;
    }
    $q('#copy_items').val().each(function (i, obj) {
    $q.ajax({
    url: 'http://'+window.location.hostname+"/admin/catalog/product/copy/id/"+item+"/field/"+i+"/",
    data: {form_key: window.FORM_KEY},
    context: document.body
    }).done(function(res) {
    $q('#'+i+'_container').html(res.res);
    })
    });
    }

    function copyitem(mfr)
    {
        $q('#searchPicked').val(mfr);
        $q('#picked').html(mfr);
        togglePicked(id);
    }

    function getHighlightSearch()
    {
    var qid = $q('#highlight_search').val();
    $q.ajax({
    url: 'http://'+window.location.hostname+"/admin/catalog/product/search/text/"+qid,
    data: {form_key: window.FORM_KEY},
    context: document.body
    }).done(function(res) {
    $q('#highlight_results').html(res.res);
    });
    }
    </script>

<?php endif; ?>
