<?php
?>
<h1>Last Custom Import</h1>
<?php $imp = $this->getLastImport(); ?>
ID : <?= $imp->getId() ?>
<br>
Successful : <?= $imp->getSucceeded() ?>
<br>
<a target="_blank" href="../../importer/import/view/import_id/<?= $imp->getId() ?>">View</a>
<h1>Pages Missing Description</h1>
<?php echo count($this->getMissingInfoPages()); ?>
<h1>Last Edited Products</h1>
<?php
var_dump(count($this->getYesterdayProducts()));
?>
<h1>Last Edited Pages</h1>
<?php
var_dump(count($this->getYesterdayPages()));
?>
ADVISE OTHER INFORMATION YOU WOULD LIKE TO SEE HERE.