<?php
$tech = $this->getProduct()->getData('highlights');
$info = json_decode($tech, true);
$count = 0;
?>
<div id="highlight_container" style="width:900px; margin:auto;">
    <?php if (count($info) > 0) : ?>
    <?php foreach ($info as $i) : ?>
            <?php if (!is_null($i)) : ?>
        <div class="specs_row" id="highlight_<?= $count ?>">
            <div class="draggable-handle"></div>
            <label for="highlight_<?= $count ?>">Highlight <?= $count++ ?></label>
            <input id="hightlight_<?= $count ?>" style="width:90%;" data-form-part="product_form" value="<?= $i ?>" name="highlights[<?= $count ?>]" />
        <a class="delete_icon" src="javascript:void(0)" onclick="deleteHighlight('highlight_<?= $count ?>')"></a>
        </div>
        <?php $count++ ?>
            <?php endif ?>
    <?php endforeach ?>
    <?php endif ?>
</div>
<button onclick="addHighlight()">Add Highlight</button>
<select class="search_select" id="copy_from_highlights">
    <option value="-1">SKU | Name</option>
    <?php foreach ($this->getProducts() as $p) : ?>
        <option value="<?= $p->getId() ?>"><?= $p->getSku() ?> | <?= $p->getName() ?></option>
    <?php endforeach; ?>
</select>
<button onclick="copyhighlight()">Copy from</button>

<script>
    var $q = jQuery.noConflict();

    function copyhighlight()
    {
        var theid = $q('#copy_from_highlights').val();
        $q.ajax({
            url: 'http://'+window.location.hostname+"/admin/catalog/product/copy/id/"+theid+"/field/highlights/",
            data: {form_key: window.FORM_KEY},
            context: document.body
        }).done(function(res) {
            var q = res.res;
            $q('#highlight_container').html(q);
        });
    }

    $q( document ).ready(function() {
        $q('#highlight_container').sortable({
            handle: '.draggable-handle',
            revert: 300,
            placeholder: "ui-state-highlight myHover",
            tolerance: "intersect",
        }).disableSelection();
    });
    function addHighlight()
    {
        var counts = $q('#highlight_container input').length;
        var clb = counts+1;
        $q('#highlight_container').append
        ('<div class="specs_row" id="highlight_'+counts+'"><div class="draggable-handle"></div><label for=-"highlight_'+counts+'">Highlight '+clb+'</label>' +
            '<input id="highlight_'+counts+'" style="width:90%;" data-form-part=\'product_form\' name=\'highlights["'+clb+'"]\' />' +
            "<a class=\"delete_icon\" src=\"javascript:void(0)\" onclick=\"deleteHighlight('highlight_"+counts+"')\"></a><br/></div>");
    }

    function deleteHighlight(h)
    {
        $q('#'+h).remove();
    }
</script>