<script>
    var $q = jQuery.noConflict();

    $q( document ).ready(function() {
        $q('#highlight_table > tbody').sortable({
            handle: '.draggable-handle3',
            revert: 300,
            placeholder: "jqplaceholder",
            tolerance: "intersect",
        }).disableSelection();

    });
    function addHighlight()
    {
        var counts = $q('#highlight_table > tbody > tr').length;
        var clb = counts+1;
        var q = '';

        q += '<tr id="highlight_row_'+clb+'">'+
            '<td class="data-grid-draggable-row-cell">'+
            '<div class="draggable-handle3"></div></td>'+
            '<td class="posrow">'+clb+'</td><td>'+
            '<input class="admin__control-text" style="width:100%" data-form-part="product_form" id="highlights[' + clb + ']["value"]" name="highlights[' + clb + ']["value"]"' +
            ' style="width:100%; padding:3px;" value="" />'+
            '</td><td><a href"#" onclick="deleteHighlight(\'highlight_row_'+clb+'\')"><img style="width:20px;" ' +
            'src="<?= $this->getViewFileUrl('Gradus_Catalog::images/trash.png'); ?>"></a></td></tr>';
        $q('#highlight_table > tbody').append(q);
    }

    function copyHighlight(vals)
    {
        $q('#highlight_table > tbody').html("");
            $q.each(vals, function (i, v) {
                var counts = $q('#highlight_table > tbody > tr').length;
                var clb = counts + 1;
                var q = '';
                q += '<tr id="highlight_row_' + clb + '">' +
                    '<td class="data-grid-draggable-row-cell">' +
                    '<div class="draggable-handle3"></div></td>' +
                    '<td class="posrow">' + clb + '</td><td>' +
                    '<input class="admin__control-text" style="width:100%" data-form-part="product_form" id="highlights[' + clb + ']["value"]" name="highlights[' + clb + ']["value"]"' +
                    ' style="width:100%; padding:3px;" value="' + v + '" />' +
                    '</td><td><a href"#" onclick="deleteHighlight(\'highlight_row_' + clb + '\')"><img style="width:20px;" ' +
                    'src="<?= $this->getViewFileUrl('Gradus_Catalog::images/trash.png'); ?>"></a></td></tr>';
                $q('#highlight_table > tbody').append(q);
            })
    }

    function deleteHighlight(h)
    {
        $q('#'+h).remove();
        $q('.posrow').each(function(i, obj) {
            var ii = i+1;
            $q(this).html(ii);
        });
    }
</script>

<?php
$tech = $this->getProduct()->getData('highlights');
$info = json_decode($tech, true);
$count = 1;
?>
<div style="width:800px;" id="highlights_container">
    <table id="highlight_table" class="admin__dynamic-rows data-grid">
        <thead>
        <tr>
            <th class="data-grid-draggable-row-cell"></th>
            <th class="data-grid-th position" style="width:30px"><span>Seq</span></th>
            <th class="data-grid-th"><span>Highlight Text</span></th>
            <th style="width:40px;" />
        </tr>
        </thead>
        <tbody>
        <?php if (count($info) > 0) : ?>
    <?php foreach ($info as $i) : ?>
        <tr id="highlight_row_<?= $count ?>">
            <td class=""data-grid-draggable-row-cell">
            <div class="draggable-handle3"></div>
            </td>
            <td class="posrow">
                <?= $count ?>
            </td>
            <td>
                <input data-form-part="product_form" name="highlights[<?= $count ?>[value]" class="admin__control-text" style="width:100%" value="<?= $i ?>" />
            </td>
            <td><a onclick="deleteHighlight('highlight_row_<?= $count ?>')" href"#"><img src="<?= $this->getViewFileUrl('Gradus_Catalog::images/trash.png'); ?>" style="width:20px"></a></td>
        </tr>
                <?php $count++ ?>
            <?php endforeach; ?>
        <?php else : ?>
            <tr id="highlight_row_<?= $count ?>">
                <td class=""data-grid-draggable-row-cell">
                <div class="draggable-handle3"></div>
                </td>
                <td class="posrow">
                    <?= $count ?>
                </td>
                <td>
                    <input data-form-part="product_form" name="highlights[<?= $count ?>[value]" class="admin__control-text" style="width:100%" value="" />
                </td>
                <td><a onclick="deleteHighlight('highlight_row_<?= $count ?>')" href"#"><img src="<?= $this->getViewFileUrl('Gradus_Catalog::images/trash.png'); ?>" style="width:20px"></a></td>
            </tr>
        <?php endif ?>
        </tbody>
        </table>
</div>
<button class="action-secondary" style="margin-right:5px;" onclick="addHighlight()">Add Highlight</button>