<?php
$tech = $this->getProduct()->getData('highlights');
$info = json_decode($tech, true);
$count = 1;
?>
<div style="width:800px;" id="highlights_container">
    <?php if (count($info) > 0) : ?>
    <table id="highlight_table" class="admin__dynamic-rows data-grid">
        <thead>
        <tr>
            <th class="data-grid-draggable-row-cell"></th>
            <th class="data-grid-th position" style="width:30px"><span>Seq</span></th>
            <th class="data-grid-th"><span>Highlight Text</span></th>
            <th style="width:100px"/>
        </tr>
        </thead>
        <tbody>
    <?php foreach ($info as $i) : ?>
        <tr id="highlight_row_<?= $count ?>">
            <td class=""data-grid-draggable-row-cell">
            <div class="draggable-handle3"></div>
            </td>
            <td class="posrow">
                <?= $count ?>
            </td>
            <td>
                <input style="width:100%; padding:3px;" value="<?= $i ?>" />
            </td>
            <td><a onclick="deleteHighlight('highlight_row_<?= $count ?>')" href"#">Remove</a></td>
        </tr>
        <?php $count++ ?>
    <?php endforeach; ?>
        </tbody>
        </table>
    <?php endif ?>
</div>

<h4 id="copyToggle" onclick="toggleSearch()">Copy From (Hide)</h4>
<div id="searchContainer" style="border:1px solid; width:750px; padding:10px;">
<div class="admin__action-multiselect-search-wrap" style="width:400px; display:inline-block">
    <input onkeyup="getHighlightSearch()" id="highlight_search" class="admin__control-text admin__action-multiselect-search" type="text">
    <label class="admin__action-multiselect-search-label"></label>
</div>
        <select multiple style="display: inline-block; max-height:250px; overflow:auto;" id="copy_items">
            <option value="name">Name</option>
            <option value="categories">Categories</option>
            <option value="highlights">Highlights</option>
            <option value="techspecs">Specifications</option>
            <option value="description">Description</option>
            <option value="InTheBox">Includes</option>
            <option value="features">Features</option>
            <option value="images">Images & Videos</option>
            <option value="seo">Seo Information</option>
            <option value="related">Related Products</option>
            <option value="accessories">Accessories</option>
            <option value="compatibility">Compatibility</option>
            <option values="downloads">Downloadable Files</option>
        </select>
    <button type="button" class="action-secondary" onclick="runCopy()" style="display:inline-block">Copy fields</button>
    <div  style="display:none;">
        <input id="searchPicked" />
    </div>
    <div id="highlight_results" style="max-height:250px; overflow:auto;">

    </div>
</div>

<script>
    var $q = jQuery.noConflict();

    function runCopy()
    {
        var fields = $q('#copy_items').val();
        var item = $q('#searchPicked').val();
        if (item == "") {
            alert("Please choose an item to copy from!");
            return;
        }
        $q('#copy_items').val().each(function (i, obj) {
            $q.ajax({
                url: 'http://'+window.location.hostname+"/admin/catalog/product/copy/id/"+item+"/field/"+i+"/",
                data: {form_key: window.FORM_KEY},
                context: document.body
            }).done(function(res) {
                $q('#'+i+'_container').html(res.res);
            })
        });
    }

    function toggleSearch()
    {
        $q('#searchContainer').toggle();
        if ($q('#searchContainer').is(':visible')) {
            $q('#copyToggle').text("Copy From (Hide)");
        } else {
            $q('#copyToggle').text("Copy From (Show)");
        }
    }

    function copyitem(mfr)
    {
        $q('#searchPicked').val(mfr);
    }

    function getHighlightSearch()
    {
        var qid = $q('#highlight_search').val();
        $q.ajax({
            url: 'http://'+window.location.hostname+"/admin/catalog/product/search/text/"+qid,
            data: {form_key: window.FORM_KEY},
            context: document.body
        }).done(function(res) {
            $q('#highlight_results').html(res.res);
        });
    }


    function copyhighlight()
    {
        var theid = $q('#copy_from_highlights').val();
        $q.ajax({
            url: 'http://'+window.location.hostname+"/admin/catalog/product/copy/id/"+theid+"/field/highlights/",
            data: {form_key: window.FORM_KEY},
            context: document.body
        }).done(function(res) {
            $q('#highlight_container').html(q);
        });
    }

    $q( document ).ready(function() {
        $q('#highlight_container2 > table > tbody').sortable({
            handle: '.draggable-handle3',
            revert: 300,
            placeholder: "jqplaceholder",
            tolerance: "intersect",
            update: function( event, ui ) {
                $q('.highlight_drag').each(function(i, obj) {
                    var ii = i+1;
                    $q(this).html(ii);
                })
                $q('.posrow').each(function(i, obj) {
                    var ii = i+1;
                    $q(this).html(ii);
                })
            }
        }).disableSelection();

    });
    function addHighlight()
    {
        var counts = $q('#highlight_table > tbody > tr').length;
        var clb = counts+1;
        var q = '';

            q += '<tr id="highlight_row_'+clb+'">'+
                '<td class="data-grid-draggable-row-cell">'+
                '<div class="draggable-handle3"></div></td>'+
                '<td class="posrow">'+clb+'</td><td>'+
                '<input style="width:100%; padding:3px;" value="" />'+
                '</td><td><a href"#" onclick="deleteHighlight(\'highlight_row_'+clb+'\')">Remove</a></td></tr>';
        $q('#highlight_table > tbody').append(q);
    }

    function deleteHighlight(h)
    {
        $q('#'+h).remove();
        $q('.posrow').each(function(i, obj) {
            var ii = i+1;
            $q(this).html(ii);
        });
    }
</script>