<?php
$im = $this->getImport();
$message = $im->getData('messages');
$mes = json_decode($message);
?>
<div style="font-size:140%"><b>Process: </b><?= $im->getData('process') ?></div>

<table style="width:1200px;" class="bord" id="messages">
    <thead>
    <tr>
        <th>Time</th>
        <th>SKU</th>
        <th>Type</th>
        <th>Message</th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($mes as $m) : ?>
    <tr class="<?= $m->type ?>">
        <td class="bord"><?= $m->time ?></td>
        <td class="bord"><?= $m->sku ?></td>
        <td class="bord"><?= $m->type ?></td>
        <td class="bord"><?= $m->mes ?></td>
    </tr>
    <?php endforeach ?>
    </tbody>
</table>

<style>
    .dataTables_wrapper .dataTables_info {
        clear:none;
        margin-left:10px;
        padding-top:0;
    }
    .bord {
        border: 1px solid black;
        border-collapse: collapse;
    }
    .error {
        background: #ff6666 !important;
    }
    .debug {
        background: #ffff99 !important;
    }
    .success {
        background : #acfbac !important;
    }
</style>